name             'henry-ghost'
maintainer       'Chris Pressland'
maintainer_email 'mail@cpressland.io'
license          'All rights reserved'
description      'Installs/Configures henry-ghost'
long_description 'Installs/Configures henry-ghost'
version          '0.1.0'

depends		'docker'
depends   'yum'
depends   'firewalld'
depends   'selinux'
